version: '3.8'

services:
  redis-cache:
    image: redis:7-alpine
    container_name: sipnplay-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-dev-data:
    driver: local